version: "3"

services:
  rdftex:
    build: ./rdftex
    container_name: rdftex
    volumes:
      - ./rdftex:/src
      - ./tex:/tex
    network_mode: host

  rdftex-watch:
    build: ./rdftex
    container_name: rdftex
    volumes:
      - ./rdftex:/src
      - ./tex:/tex
    network_mode: host
    entrypoint: ./preprocessor.py watch

  minskg:
    build: ./minskg
    ports:
    - "5000:5000"
    volumes:
      - ./minskg:/src
      - ./tex:/tex
    
  latexmk:
    build: ./rdftex
    container_name: latexmk
    volumes:
      - ./tex:/tex
    entrypoint: latexmk -pvc -pdf -xelatex -cd /tex/example.tex
